apiVersion: apps/v1
kind: Deployment
metadata:
  name: agmetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agmetrics
  template:
    metadata:
      labels:
        app: agmetrics
    spec:
      containers:
        - name: agmetrics
          image: msteenhu/agmetrics:0.0.2
          volumeMounts:
            - name: ub
              mountPath: /ub
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: ub
          hostPath:
            path: /ub
            type: Directory
