apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: quay.io/prometheus/node-exporter:latest
          args: 
            - '--path.rootfs=/host'
          volumeMounts:
            - name: root
              mountPath: /host
      volumes:
        - name: root
          hostPath:
            path: /
            type: Directory
