apiVersion: v1
kind: Service
metadata:
  name: agmetrics-service
spec:
  type: NodePort
  selector:
    app: agmetrics
  ports:
    - name: http
      port: 9360
      targetPort: 9360
      nodePort: 30000
